### ISSUE TITLE
Possible Mistake in Description of Array Dimensions

### ISSUE THREAD

**Issue by ewestrich** [learn-co-curriculum/dsc-scalars-vectors-matrices-tensors-codealong#1]
I believe this paragraph has a typo in its description of previous arrays:

Shape of an array
The shape (or "dimensions") of a vector/matrix array tells us the number of values for each dimension. For a 2-dimensional array it gives you the number of rows and the number of columns. Let’s find the shape of our preceding 2-D and 3-D arrays created above. For a NumPy object, you can access its shape as shown below:

print(x.shape) # the vector with 10 scalars
print (X.shape) # the 2-D Matrix with 3X3 scalar components

It says "2-D and 3-D arrays created above" but is actually referring to 1-D and 2-D arrays.

Thanks!

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by Cheffrey2000** [comment]
Thank you for raising this issue. After reviewing the text, it has been determined to be accurate the way it is written. A vector is a 1-D array.
